#!/usr/bin/env bash
#
# Rebuilds the self-hosted Material Symbols subset in src/fonts.
#
# In src rather than public so the bundler fingerprints it and rewrites the URL
# for whatever base the site is served from.
#
# The font stays VARIABLE after subsetting. FILL is the axis that matters: M3
# draws an unselected control's icon outlined and a selected one's filled, and
# on a variable font that is an axis to animate rather than two icons to
# cross-fade. See src/styles/components/icon.css.
#
# Requires: python3, curl. Creates a throwaway venv under .cache/.
#
# Usage:  ./scripts/build-icon-font.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/src/fonts"
VENV="$ROOT/.cache/fonttools-venv"

MS_BASE="https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D"
MS_URL="$MS_BASE.ttf"
MS_CODEPOINTS_URL="$MS_BASE.codepoints"
MS_LICENSE_URL="https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE"

if [[ ! -x "$VENV/bin/pyftsubset" ]]; then
  echo "==> creating fonttools venv"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet fonttools brotli
fi

mkdir -p "$OUT"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> Material Symbols Rounded (FILL + wght + GRAD + opsz)"
curl -sL "$MS_URL" -o "$TMP/ms.ttf"
curl -sL "$MS_CODEPOINTS_URL" -o "$TMP/ms.codepoints"

ICON_NAMES=$(grep -vE '^\s*(#|$)' "$ROOT/scripts/icons.txt")
MISSING=""
CODEPOINTS=""
for name in $ICON_NAMES; do
  cp=$(awk -v n="$name" '$1 == n { print $2; exit }' "$TMP/ms.codepoints")
  if [[ -z "$cp" ]]; then
    MISSING="$MISSING $name"
  else
    CODEPOINTS="${CODEPOINTS:+$CODEPOINTS,}U+$cp"
  fi
done

if [[ -n "$MISSING" ]]; then
  echo "error: no such Material Symbol:$MISSING" >&2
  echo "Check the name at https://fonts.google.com/icons" >&2
  exit 1
fi

# Subsetted by CODEPOINT, not by ligature name: pyftsubset closes over GSUB, so
# `--text="search person ..."` drags in every ligature those letters can form -
# thousands of glyphs. The PUA codepoints give exactly the icons asked for.
#
# --layout-features='' drops GSUB entirely; we address icons by codepoint, so
# the ligature table is dead weight.
"$VENV/bin/pyftsubset" "$TMP/ms.ttf" \
  --output-file="$OUT/material-symbols-rounded.woff2" \
  --flavor=woff2 \
  --unicodes="$CODEPOINTS" \
  --layout-features='' \
  --no-hinting
curl -sL "$MS_LICENSE_URL" -o "$OUT/material-symbols-LICENSE.txt"

# Emit the name -> codepoint map so <Icon name="..."> is typed against the set
# of icons actually in the font.
{
  echo "// GENERATED by ./scripts/build-icon-font.sh from scripts/icons.txt."
  echo "// Add an icon there and re-run the script; do not edit this file."
  echo
  echo "export const ICONS = {"
  for name in $ICON_NAMES; do
    cp=$(awk -v n="$name" '$1 == n { print $2; exit }' "$TMP/ms.codepoints")
    echo "  $name: '\\u$cp',"
  done
  echo "} as const"
  echo
  echo "export type IconName = keyof typeof ICONS"
} > "$ROOT/src/components/icons.generated.ts"

echo "==> done: $(ls -lh "$OUT/material-symbols-rounded.woff2" | awk '{print $5}')"
